# PyTorch Basics

https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/01-basics/pytorch_basics/main.py

In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

## autograd

In [5]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# 計算グラフを作成
# y = 2x + 3
y = w * x + b
print(y)

# 勾配の計算
y.backward()

print(x.grad)  # dy/dx = w
print(w.grad)  # dy/dw = x
print(b.grad)  # dy/db = 1

tensor(5., grad_fn=<AddBackward0>)
tensor(2.)
tensor(1.)
tensor(1.)


## lossのautograd

In [11]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

linear = nn.Linear(3, 2)
print(linear.weight)
print(linear.bias)

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

pred = linear(x)

loss = criterion(pred, y)
print('loss:', loss.item())

loss.backward()

print(linear.weight.grad)  # dL/dw
print(linear.bias.grad)    # dL/db

optimizer.step()

Parameter containing:
tensor([[-0.1036,  0.1211,  0.1574],
        [ 0.2728,  0.3966,  0.1372]], requires_grad=True)
Parameter containing:
tensor([-0.1688, -0.3736], requires_grad=True)
loss: 1.9540483951568604
tensor([[-0.0999, -0.3432,  0.9634],
        [-0.0609,  1.0102,  0.3925]])
tensor([-0.5188, -0.6742])


In [12]:
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization:', loss.item())

loss after 1 step optimization: 1.924679160118103


## Loading data from numpy