In [89]:
%matplotlib inline
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, Adam
import numpy as np
import matplotlib.pyplot as plt

In [58]:
# ランダムシードは固定するべし
# 結果を再現・アルゴリズムを比較するため
np.random.seed(7)

In [59]:
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data

--2017-05-26 17:02:49--  http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data
Resolving archive.ics.uci.edu... 128.195.10.249
Connecting to archive.ics.uci.edu|128.195.10.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23279 (23K) [text/plain]
Saving to: ‘pima-indians-diabetes.data.2’

pima-indians-diabet 100%[===================>]  22.73K  --.-KB/s    in 0.1s    

2017-05-26 17:02:49 (174 KB/s) - ‘pima-indians-diabetes.data.2’ saved [23279/23279]



In [60]:
dataset = np.loadtxt('pima-indians-diabetes.data', delimiter=',')

In [61]:
dataset

array([[   6.   ,  148.   ,   72.   , ...,    0.627,   50.   ,    1.   ],
       [   1.   ,   85.   ,   66.   , ...,    0.351,   31.   ,    0.   ],
       [   8.   ,  183.   ,   64.   , ...,    0.672,   32.   ,    1.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,    0.245,   30.   ,    0.   ],
       [   1.   ,  126.   ,   60.   , ...,    0.349,   47.   ,    1.   ],
       [   1.   ,   93.   ,   70.   , ...,    0.315,   23.   ,    0.   ]])

In [119]:
X = dataset[:, 0:8]
Y = dataset[:, 8]

In [133]:
from sklearn import preprocessing
X_scaled = preprocessing.scale(X)
print(X_scaled.shape)
print(X_scaled.mean(axis=0))
print(X_scaled.std(axis=0))

(768, 8)
[ -7.74843153e-17   3.61400724e-18  -1.32724416e-17   7.76288755e-17
  -5.49329101e-17   2.97273780e-15   1.92438658e-15   2.19297959e-16]
[ 1.  1.  1.  1.  1.  1.  1.  1.]


In [176]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(X_scaled, Y, epochs=150, batch_size=10)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_88 (Dense)             (None, 12)                108       
_________________________________________________________________
dense_89 (Dense)             (None, 8)                 104       
_________________________________________________________________
dense_90 (Dense)             (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________
Epoch 1/150
768/768 [==============================] - 1s - loss: 0.6448 - acc: 0.6719     
Epoch 2/150
768/768 [==============================] - 0s - loss: 0.5721 - acc: 0.7253     
Epoch 3/150
768/768 [==============================] - 0s - loss: 0.5276 - acc: 0.7500     
Epoch 4/150
768/768 [==============================] - 0s - loss: 0.5052 - acc: 0.7526     
Epoch 5/150
768/768 [===================

In [138]:
scores = model.evaluate(X_scaled, Y)

 32/768 [>.............................] - ETA: 0s

In [139]:
print('%s: %.2f%%' % (model.metrics_names[1], scores[1] * 100))

acc: 83.72%


In [143]:
predictions = model.predict(X_scaled)

In [144]:
rounded = [round(x[0]) for x in predictions]

In [148]:
print(rounded[:10])
print(Y[:10])

[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0]
[ 1.  0.  1.  0.  1.  0.  1.  0.  1.  1.]


## Functional API

In [157]:
from keras.layers import Input, Dense
from keras.models import Model

inputs = Input(shape=(8, ))
x = Dense(12, activation='relu')(inputs)
x = Dense(8, activation='relu')(x)
predictions = Dense(1, activation='sigmoid')(x)

model = Model(inputs=inputs, outputs=predictions)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 8)                 0         
_________________________________________________________________
dense_85 (Dense)             (None, 12)                108       
_________________________________________________________________
dense_86 (Dense)             (None, 8)                 104       
_________________________________________________________________
dense_87 (Dense)             (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [159]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(X_scaled, Y, epochs=150, batch_size=10)

Epoch 1/150
768/768 [==============================] - 1s - loss: 0.4722 - acc: 0.7799     
Epoch 2/150
768/768 [==============================] - 0s - loss: 0.4649 - acc: 0.7826     
Epoch 3/150
768/768 [==============================] - 0s - loss: 0.4604 - acc: 0.7852     
Epoch 4/150
768/768 [==============================] - 0s - loss: 0.4575 - acc: 0.7839     
Epoch 5/150
768/768 [==============================] - 0s - loss: 0.4551 - acc: 0.7865     
Epoch 6/150
768/768 [==============================] - 0s - loss: 0.4518 - acc: 0.7852     
Epoch 7/150
768/768 [==============================] - 0s - loss: 0.4497 - acc: 0.7839     
Epoch 8/150
768/768 [==============================] - 0s - loss: 0.4485 - acc: 0.7799     
Epoch 9/150
768/768 [==============================] - 0s - loss: 0.4467 - acc: 0.7812     
Epoch 10/150
768/768 [==============================] - 0s - loss: 0.4451 - acc: 0.7786     
Epoch 11/150
768/768 [==============================] - 0s - loss: 0.4432 - acc

## Save and load a model

In [165]:
model_json = model.to_json()
with open('model.json', 'w') as json_file:
    json_file.write(model_json)
model.save_weights('model.h5')

In [167]:
del model

In [170]:
from keras.models import model_from_json
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights('model.h5')

In [172]:
loaded_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 8)                 0         
_________________________________________________________________
dense_85 (Dense)             (None, 12)                108       
_________________________________________________________________
dense_86 (Dense)             (None, 8)                 104       
_________________________________________________________________
dense_87 (Dense)             (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [175]:
del loaded_model

In [177]:
model.save('mymodel.h5')

In [178]:
del model

In [180]:
from keras.models import load_model
model = load_model('mymodel.h5')

In [181]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_88 (Dense)             (None, 12)                108       
_________________________________________________________________
dense_89 (Dense)             (None, 8)                 104       
_________________________________________________________________
dense_90 (Dense)             (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [183]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [184]:
model.optimizer